development:
  adapter: postgresql
  encoding: unicode
  database: rails_sample_app
  pool: 5
  username: rails_sample
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rails_sample_app
  pool: 5
  username: rails_sample
  password:
  
production:
  adapter: postgresql
  encoding: unicode
  database: rails_sample_app
  pool: 5
  username: rails_sample
  password: